// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pg

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AktActivity struct {
	ID     uuid.UUID
	TripID uuid.UUID
	Title  string
	Date   pgtype.Timestamp
}

type AktLink struct {
	ID     uuid.UUID
	TripID uuid.UUID
	Title  string
	Url    string
}

type AktParticipant struct {
	ID        uuid.UUID
	TripID    uuid.UUID
	Email     string
	Confirmed bool
}

type AktTrip struct {
	ID          uuid.UUID
	Destination string
	OwnerEmail  string
	OwnerName   string
	Confirmed   bool
	StartAt     pgtype.Timestamp
	EndAt       pgtype.Timestamp
}
