services:
  db:
    image: postgres:13
    restart: unless-stopped
    ports:
      - 5446:5432
    environment:
      POSTGRES_USER: pg-test
      POSTGRES_PASSWORD: 1329
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - 8080:8080
    environment:
      JOURNEY_DATABASE_PORT: ${JOURNEY_DATABASE_PORT_DOCKER:-5432}
      JOURNEY_DATABASE_HOST: ${JOURNEY_DATABASE_HOST_DOCKER:-db}
    depends_on:
      - db

volumes:
  db:
    driver: local