apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nlw-journey
  namespace: argocd

spec:
  project: default
  source:
    repoURL: 'git@github.com:Sandrolaxx/trip-pass-go.git'
    targetRevision: HEAD
    path: ./devops/k8s-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: journey
  syncPolicy:
    automated:
      prune: true