CREATE TABLE IF NOT EXISTS AKT_TRIP (
    ID UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    DESTINATION VARCHAR(255) NOT NULL,
    OWNER_EMAIL VARCHAR(255) NOT NULL,
    OWNER_NAME VARCHAR(255) NOT NULL,
    CONFIRMED BOOLEAN NOT NULL DEFAULT FALSE,
    START_AT TIMESTAMP NOT NULL,
    END_AT TIMESTAMP NOT NULL
);
---- create above / drop below ----

DROP TABLE IF EXISTS AKT_TRIP;