CREATE TABLE IF NOT EXISTS AKT_PARTICIPANT (
    ID UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    TRIP_ID UUID NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CONFIRMED BOOLEAN NOT NULL DEFAULT FALSE,

    FOREIGN KEY (TRIP_ID) REFERENCES AKT_TRIP(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

---- create above / drop below ----

DROP TABLE IF EXISTS PARTICIPANT;
