CREATE TABLE IF NOT EXISTS AKT_LINK (
    ID UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    TRIP_ID UUID NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    URL VARCHAR(255) NOT NULL,

    FOREIGN KEY (TRIP_ID) REFERENCES AKT_TRIP(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

---- create above / drop below ----

DROP TABLE IF EXISTS LINK;
