replicaCount: 5

image:
  repository: sandrolax/api-journey
  tag: "4388865"
  pullPolicy: IfNotPresent
  containerPort: 8080

# Utilizado para imagens privadas
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

podSecurityContext: {}
securityContext: {}

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

#Utilizado para self-healing do k8s, aqui podemos add health-check
# livenessProbe:
#   httpGet:
#     paths: /
#     port: http
#readinessProbe:
#   httpGet:
#     paths: /
#     port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
  #targetMemoryUtilizationPercentage: 75

volumes: []
nodeSelector: {}
tolerations: []
affinity: {}
