name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: "Build and Push"
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t sandrolax/api-journey:${{ steps.generate_sha.outputs.sha }} .
        
      - name: Push to registry
        run: | 
          docker push sandrolax/api-journey:${{ steps.generate_sha.outputs.sha }}
          docker tag sandrolax/api-journey:${{ steps.generate_sha.outputs.sha }} sandrolax/api-journey:ubuntu-latest
          docker push sandrolax/api-journey:latest
